import random

WELCOME_TEMPLATES = [
    "Selamat datang {mentions}! Yuk segera verifikasi akun kamu di #rules, setelah itu langsung merapat ke main-chat buat ngobrol dan kenalan sama teman-teman yang lain! 🎉",
    "Halo {mentions}! Jangan lupa verifikasi dulu ya di #rules, terus lanjut gabung seru-seruan di main-chat! 🚀",
    "Welcome {mentions}! Langkah pertama: verify dulu di #rules. Langkah kedua: nimbrung di main-chat! Gaskan! 🔥",
    "Hai {mentions}! Selamat bergabung! Segera verify di #rules ya, setelah itu kita tunggu di main-chat! 😊",
    "{mentions} hadir! Ayo langsung verify di #rules, terus lanjut ngobrol santai di main-chat! 💬",
    "Selamat datang {mentions}! Komunitas kita makin seru! Verify dulu di #rules, baru gas ke main-chat! 🎊",
    "Halo {mentions}! Senang kalian gabung! Langkah pertama: verify akun di #rules. Langkah kedua: join obrolan di main-chat! 🎯",
    "{mentions} baru join! Yuk langsung verify di #rules, setelah itu kita ngobrol-ngobrol di main-chat! 👋",
    "Welcome aboard {mentions}! Siap-siap seru-seruan! Verify dulu di #rules, terus lanjut ke main-chat! 🚀",
    "Hai {mentions}! Selamat datang di Algonova! Jangan lupa verify dulu di #rules, habis itu langsung main ke main-chat! 🔥",
    "{mentions} resmi bergabung! Step pertama: verify di #rules. Step kedua: aktif di main-chat! Yuk! 🎉",
    "Halo {mentions}! Kami senang kalian jadi bagian dari komunitas ini! Verify dulu ya di #rules, terus gabung di main-chat! 🌟",
    "Selamat datang {mentions}! Perjalanan kalian dimulai di sini! Verify di #rules, lalu explore main-chat! 💪",
    "{mentions} masuk! Langsung verify di #rules, setelah itu bebas ngobrol dan belajar di main-chat! 📚",
    "Hai {mentions}! Selamat bergabung! Yuk selesaikan verifikasi di #rules, terus kita ngumpul di main-chat! 😎",
    "Welcome {mentions}! Algonova makin rame! Verify dulu di #rules, baru lanjut ke main-chat buat kenalan! 🎊",
    "Halo {mentions}! Senang punya anggota baru kayak kalian! Segera verify di #rules, setelah itu kita ngobrol di main-chat! 🤗",
    "{mentions} datang! Jangan lupa verify akun di #rules, habis itu langsung nimbrung di main-chat! 🔥",
    "Selamat datang {mentions}! Ada banyak teman dan ilmu seru menanti! Verify di #rules, lalu join main-chat! 🚀",
    "Hai {mentions}! Step pertama: verify di #rules. Step kedua: aktif di main-chat. Simple kan? 😄",
    "{mentions} hadir meramaikan server! Yuk verify dulu di #rules, terus gabung diskusi seru di main-chat! 🎯",
    "Halo {mentions}! Kamu pasti bakal betah di sini! Ayo verify di #rules, lanjut ngobrol di main-chat! 😊",
    "Welcome {mentions}! Mulai petualangan kalian dengan verifikasi di #rules, lalu explore main-chat! 🌟",
    "{mentions} join! Siap-siap belajar coding sambil seru-seruan! Verify di #rules, terus ke main-chat! 💻",
    "Selamat datang {mentions}! Komunitas belajar paling seru ada di sini! Verify di #rules, lalu gas ke main-chat! 🎮",
    "Hai {mentions}! Senang kalian bergabung! Langsung verify di #rules, setelah itu kita ngobrol di main-chat! 👋",
    "Halo {mentions}! Ada yang baru nih! Verify dulu di #rules, terus lanjut kenalan di main-chat! 🎉",
    "{mentions} resmi jadi warga Algonova! Jangan lupa verify di #rules, abis itu langsung aktif di main-chat! 🔥",
    "Selamat datang {mentions}! Yuk mulai dengan verifikasi di #rules, lalu gabung obrolan seru di main-chat! 💬",
    "Hai {mentions}! Kami tunggu kalian di #rules buat verifikasi, terus lanjut ngobrol di main-chat ya! 😊",
    "Welcome {mentions}! Semoga betah dan dapet banyak teman baru! Verify di #rules, lalu main ke main-chat! 🚀",
    "{mentions} baru hadir! Segera verify akun di #rules, setelah itu langsung join seru-seruan di main-chat! 🎊",
    "Halo {mentions}! Selamat bergabung di keluarga besar Algonova! Verify di #rules, lalu ngobrol di main-chat! 🏠",
    "Selamat datang {mentions}! Ada banyak challenge seru nunggu kalian! Verify di #rules, terus ke main-chat! 🏆",
    "Hai {mentions}! Jangan jadi silent reader! Verify dulu di #rules, baru aktif di main-chat! 😆",
    "{mentions} sudah bergabung! Langkah awal: verify di #rules. Langkah lanjutan: seru-seruan di main-chat! 🎯",
    "Halo {mentions}! Selamat datang! Banyak materi keren yang bisa kalian akses setelah verify di #rules! Yuk lanjut ke main-chat! 📖",
    "Welcome {mentions}! Senang kalian ada di sini! Verify di #rules dulu ya, baru kita ngobrol di main-chat! 🤗",
    "{mentions} join squad! Langsung verify di #rules, terus gas ke main-chat buat kenalan sama yang lain! 🔥",
    "Selamat datang {mentions}! Perjalanan coding kalian dimulai sekarang! Verify di #rules, lalu diskusi di main-chat! 💻",
    "Hai {mentions}! Jangan lupa verify di #rules ya, setelah itu kita tunggu di main-chat buat ngobrol santai! 😊",
    "Halo {mentions}! Verify dulu di #rules, abis itu langsung gabung di main-chat! Siapa yang paling cepat? 🚀",
    "{mentions} hadir! Waktunya verify di #rules, lanjut ngobrol dan belajar bareng di main-chat! 🎉",
    "Selamat datang {mentions}! Kami siap bantu kalian belajar! Verify di #rules, lalu join diskusi di main-chat! 🤝",
    "Hai {mentions}! Algonova terasa lebih hidup dengan kehadiran kalian! Verify di #rules, lalu main ke main-chat! 🌟",
    "Welcome {mentions}! Siap-siap petualangan baru! Verify di #rules dulu, terus lanjut ke main-chat! 🚀",
    "{mentions} baru nih! Ayo sambut! Verify di #rules, setelah itu ngobrol di main-chat! 🔥",
    "Halo {mentions}! Senang kalian memilih Algonova! Verify di #rules, lalu explore main-chat! 🎯",
    "Selamat datang {mentions}! Ada mentor dan teman yang siap bantu! Verify di #rules, lanjut ke main-chat! 👨‍🏫",
    "Hai {mentions}! Langsung verify di #rules, habis itu kita ngumpul bareng di main-chat! Yuk! 🎊",
    "{mentions} sudah resmi join! Verify dulu di #rules, terus lanjut ngobrol di main-chat! Jangan malu ya! 😊",
    "Halo {mentions}! Komunitas kita tambah seru dengan hadirnya kalian! Verify di #rules, lalu ke main-chat! 💬",
    "Welcome {mentions}! Yuk mulai dengan verifikasi di #rules, setelah itu bebas ngobrol di main-chat! 🚀",
    "Selamat datang {mentions}! Jangan lupa verify akun di #rules, lanjut ke main-chat buat kenalan! 😎",
    "Hai {mentions}! Kami期待 kalian aktif di sini! Verify di #rules, lalu gabung diskusi di main-chat! 🎯",
    "{mentions} masuk! Langsung verify di #rules, abis itu nimbrung di main-chat! Gaskeun! 🔥",
    "Halo {mentions}! Selamat bergabung! Segera verify di #rules, lalu join obrolan asyik di main-chat! 🎉",
    "Selamat datang {mentions}! Di sini kalian bisa belajar sambil bersenang-senang! Verify di #rules, terus ke main-chat! 🎮",
    "Hai {mentions}! Ada teman-teman baru yang siap kenalan! Verify dulu di #rules, baru ke main-chat! 🤗",
    "Welcome {mentions}! Mulai perjalanan seru kalian dengan verify di #rules, lalu explore main-chat! 🌟",
    "{mentions} hadir meriah! Verify dulu di #rules ya, setelah itu langsung gas ke main-chat! 🚀",
    "Halo {mentions}! Senang kalian jadi bagian dari Algonova! Verify di #rules, lalu ngobrol di main-chat! 🏆",
    "Selamat datang {mentions}! Ada weekly quest seru nunggu! Tapi verify dulu di #rules, baru ke main-chat! 🎯",
    "Hai {mentions}! Jangan sungkan-sungkan! Verify di #rules dulu, terus lanjut ke main-chat buat ngobrol! 💬",
    "{mentions} baru gabung! Yuk sambut! Verify di #rules, lalu share cerita di main-chat! 🔥",
    "Halo {mentions}! Selamat datang di server terbaik untuk belajar coding! Verify di #rules, lalu ke main-chat! 💻",
    "Welcome {mentions}! Kalian akan suka di sini! Verify di #rules dulu, terus main ke main-chat! 😊",
    "Selamat datang {mentions}! Banyak hal keren yang bisa kalian lakukan! Mulai dengan verify di #rules, lalu explore main-chat! 🚀",
    "Hai {mentions}! Langkah pertama: verify di #rules. Langkah kedua: aktif di main-chat. Langkah ketiga: jadi legend! 😎",
    "{mentions} hadir! Yuk verify dulu di #rules, terus lanjut ngobrol santai di main-chat! 🎊",
    "Halo {mentions}! Kami tunggu verifikasi kalian di #rules, setelah itu langsung join obrolan di main-chat! 👋",
    "Selamat datang {mentions}! Perjalanan kalian menuju jago coding dimulai di sini! Verify di #rules, lalu ke main-chat! 📚",
    "Hai {mentions}! Algonova makin rame berkat kalian! Verify di #rules, lalu gabung di main-chat! 🎉",
    "Welcome {mentions}! Semoga kalian betah dan aktif! Verify di #rules, terus lanjut ke main-chat! 🔥",
    "{mentions} resmi jadi bagian dari keluarga Algonova! Ayo verify di #rules, lalu ngobrol di main-chat! 🏠",
    "Halo {mentions}! Senang kalian ada! Yuk verify di #rules dulu, baru kita ngobrol-ngobrol di main-chat! 😊",
    "Selamat datang {mentions}! Ada banyak teman yang siap menyambut! Verify di #rules, lalu ke main-chat! 🤗",
    "Hai {mentions}! Langsung verify di #rules, abis itu kita tunggu di main-chat buat diskusi seru! 🚀",
    "{mentions} bergabung! Jangan lupa verify di #rules, terus aktif di main-chat! Kita tunggu ya! 🎯",
    "Halo {mentions}! Selamat bergabung di komunitas belajar yang asyik! Verify di #rules, lalu ke main-chat! 💻",
    "Welcome {mentions}! Kalian adalah anggota baru yang kita tunggu! Verify di #rules, terus main ke main-chat! 🌟",
    "Selamat datang {mentions}! Yuk bertemu dengan teman-teman baru! Mulai dengan verify di #rules, lalu ke main-chat! 💬",
    "Hai {mentions}! Jangan malu-malu! Verify dulu di #rules, setelah itu bebas ngobrol di main-chat! 😆",
    "{mentions} sudah datang! Waktunya verify di #rules, lanjut seru-seruan di main-chat! Gasken! 🔥",
    "Halo {mentions}! Kami sambut kalian dengan hangat! Verify di #rules dulu, lalu join main-chat! 🎉",
    "Selamat datang {mentions}! Ada banyak aktivitas seru! Mulai dengan verifikasi di #rules, lalu explore main-chat! 🎮",
    "Hai {mentions}! Senang kalian bergabung! Segera verify di #rules, setelah itu ngobrol di main-chat! 😊",
    "Welcome {mentions}! Siap-siap jadi programmer handal! Verify di #rules dulu, terus ke main-chat! 🚀",
    "{mentions} baru! Yuk verify di #rules, abis itu langsung aktif di main-chat! 🔥",
    "Halo {mentions}! Selamat datang! Kalian akan menemukan banyak ilmu baru di sini! Verify di #rules, lalu ke main-chat! 📖",
    "Selamat datang {mentions}! Langsung verify di #rules, terus lanjut ngobrol dan belajar di main-chat! 🎯",
    "Hai {mentions}! Kami tunggu kalian di #rules buat verifikasi, setelah itu kita ngumpul di main-chat! 🤗",
    "{mentions} hadir! Jangan lupa verifikasi akun ya di #rules! Lanjut ke main-chat buat kenalan! 👋",
    "Halo {mentions}! Selamat bergabung! Verify dulu di #rules, habis itu langsung gas ke main-chat! 🚀",
    "Welcome {mentions}! Ada teman-teman keren yang siap menyambut! Verify di #rules, lalu join main-chat! 🌟",
    "Selamat datang {mentions}! Komunitas ini penuh dengan orang-orang inspiratif! Verify di #rules, lalu ke main-chat! ✨",
    "Hai {mentions}! Ayo mulai petualangan kalian! Verify di #rules dulu, terus lanjut ke main-chat! 🎉",
    "{mentions} masuk! Langsung verify di #rules, abis itu gabung seru-seruan di main-chat! 🔥",
    "Halo {mentions}! Kami senang kalian bergabung! Yuk verify di #rules, lalu kita ngobrol di main-chat! 💬",
    "Selamat datang {mentions}! Banyak hal seru yang bisa kalian lakukan di sini! Mulai dengan verify di #rules, lalu ke main-chat! 🚀",
    "Hai {mentions}! Jangan lupa verify akun di #rules! Setelah itu, kita tunggu di main-chat buat ngobrol santai! 😊",
    "Welcome {mentions}! Kalian adalah bagian dari komunitas yang luar biasa! Verify di #rules, lalu explore main-chat! 🏆",
    "{mentions} telah bergabung! Yuk verify di #rules, terus aktif di main-chat! Kita tunggu ya! 👋",
    "Halo {mentions}! Selamat datang di Algonova! Selesaikan verifikasi di #rules, lalu join obrolan di main-chat! 🎊",
    "Selamat datang {mentions}! Ada mentor seru yang siap bimbing kalian! Verify di #rules, lalu diskusi di main-chat! 👨‍🏫",
    "Hai {mentions}! Gaskeun! Verify di #rules dulu, terus lanjut ke main-chat! 🔥",
]

SINGLE_TEMPLATES = [
    "Selamat datang {mentions}! Yuk segera verifikasi akun kamu di #rules, setelah itu langsung merapat ke main-chat buat ngobrol dan kenalan sama teman-teman yang lain! 🎉",
    "Halo {mentions}! Jangan lupa verifikasi dulu ya di #rules, terus lanjut gabung seru-seruan di main-chat! 🚀",
    "Welcome {mentions}! Langkah pertama: verify dulu di #rules. Langkah kedua: nimbrung di main-chat! Gaskan! 🔥",
    "Hai {mentions}! Selamat bergabung! Segera verify di #rules ya, setelah itu kita tunggu di main-chat! 😊",
    "{mentions} hadir! Ayo langsung verify di #rules, terus lanjut ngobrol santai di main-chat! 💬",
    "Halo {mentions}! Senang kamu gabung! Verify dulu di #rules, baru gas ke main-chat! 🎯",
    "Welcome {mentions}! Siap-siap seru-seruan! Verify dulu di #rules, terus lanjut ke main-chat! 🚀",
    "Hai {mentions}! Selamat datang di Algonova! Jangan lupa verify dulu di #rules, habis itu langsung main ke main-chat! 🔥",
    "Halo {mentions}! Kami senang kamu jadi bagian dari komunitas ini! Verify dulu ya di #rules, terus gabung di main-chat! 🌟",
    "{mentions} join! Langsung verify di #rules, setelah itu bebas ngobrol dan belajar di main-chat! 📚",
    "Selamat datang {mentions}! Perjalanan kamu dimulai di sini! Verify di #rules, lalu explore main-chat! 💪",
    "Hai {mentions}! Selamat bergabung! Yuk selesaikan verifikasi di #rules, terus kita ngumpul di main-chat! 😎",
    "Halo {mentions}! Senang punya anggota baru kayak kamu! Segera verify di #rules, setelah itu kita ngobrol di main-chat! 🤗",
    "{mentions} datang! Jangan lupa verify akun di #rules, habis itu langsung nimbrung di main-chat! 🔥",
    "Welcome {mentions}! Mulai petualangan kamu dengan verifikasi di #rules, lalu explore main-chat! 🌟",
    "Halo {mentions}! Selamat bergabung! Langsung verify di #rules, setelah itu kita ngobrol di main-chat! 👋",
    "{mentions} resmi jadi warga Algonova! Jangan lupa verify di #rules, abis itu langsung aktif di main-chat! 🔥",
    "Hai {mentions}! Kami tunggu kamu di #rules buat verifikasi, terus lanjut ngobrol di main-chat ya! 😊",
    "Halo {mentions}! Selamat bergabung di keluarga besar Algonova! Verify di #rules, lalu ngobrol di main-chat! 🏠",
    "Welcome {mentions}! Senang kamu ada di sini! Verify di #rules dulu ya, baru kita ngobrol di main-chat! 🤗",
]


def format_mentions(members):
    if not members:
        return ""
    if len(members) == 1:
        return members[0].mention
    mention_str = ", ".join(m.mention for m in members[:-1])
    return f"{mention_str}, dan {members[-1].mention}"


def get_random_welcome(members):
    mention_str = format_mentions(members)
    if len(members) == 1:
        template = random.choice(SINGLE_TEMPLATES)
    else:
        template = random.choice(WELCOME_TEMPLATES)
    return template.replace("{mentions}", mention_str)
